[package]
name = "msg-wire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tracing.workspace = true
